### ISSUE TITLE
IncompatibleClassChangeError when attempting to load a config GUI on v2.5.2

### ISSUE THREAD

**Issue by ghost** [Lortseam/completeconfig#23]
Getting this error when trying to load the config GUI for my mod after updating to v2.5.2. Not sure if this is something on my end or yours, so I apologize if it's just something I screwed up somehow. I went to look at the example mods you have to see if anything changed about the way Mod Menu integration is set up, but it doesn't look like any of them have updated to use v2.5.2 of CompleteConfig yet, so I thought I'd report just in case.

It works if I switch to YACL instead of Cloth and remove the `@ConfigEntry.Dropdown` annotations in my config, but I'd prefer to not have to do this.

```
[00:32:40] [Render thread/ERROR] (Mod Menu | ModsScreen) Error from mod 'cloth-config'
 java.lang.IncompatibleClassChangeError: class me.shedaniel.clothconfig2.gui.entries.AbstractTextFieldListListEntry$AbstractTextFieldListCell$1 overrides final method net.minecraft.client.gui.widget.ClickableWidget.render(Lnet/minecraft/client/gui/DrawContext;IIF)V
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at me.shedaniel.clothconfig2.gui.entries.DoubleListListEntry.<init>(DoubleListListEntry.java:54) ~[cloth-config-fabric-12.0.111-fabric.jar:?]
	at me.shedaniel.clothconfig2.impl.builders.DoubleListBuilder.build(DoubleListBuilder.java:151) ~[cloth-config-fabric-12.0.111-fabric.jar:?]
	at me.shedaniel.clothconfig2.ClothConfigDemo.getConfigBuilderWithDemo(ClothConfigDemo.java:94) ~[cloth-config-fabric-12.0.111-fabric.jar:?]
	at me.shedaniel.clothconfig2.fabric.ClothConfigModMenuDemo.lambda$getModConfigScreenFactory$0(ClothConfigModMenuDemo.java:35) ~[cloth-config-fabric-12.0.111-fabric.jar:?]
	at com.terraformersmc.modmenu.ModMenu.getConfigScreen(ModMenu.java:62) ~[modmenu-9.0.0.jar:?]
	at com.terraformersmc.modmenu.gui.ModsScreen.init(ModsScreen.java:106) ~[modmenu-9.0.0.jar:?]
	at net.minecraft.client.gui.screen.Screen.init(Screen.java:298) ~[minecraft-merged-2da1a7ea61-1.20.3-net.fabricmc.yarn.1_20_3.1.20.3+build.1.jar:?]
	at net.minecraft.client.MinecraftClient.setScreen(MinecraftClient.java:1187) ~[minecraft-merged-2da1a7ea61-1.20.3-net.fabricmc.yarn.1_20_3.1.20.3+build.1.jar:?]
	at com.terraformersmc.modmenu.gui.widget.ModMenuButtonWidget.lambda$new$0(ModMenuButtonWidget.java:15) ~[modmenu-9.0.0.jar:?]
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget.java:95) ~[minecraft-merged-2da1a7ea61-1.20.3-net.fabricmc.yarn.1_20_3.1.20.3+build.1.jar:?]
	at net.minecraft.client.gui.widget.PressableWidget.onClick(PressableWidget.java:48) ~[minecraft-merged-2da1a7ea61-1.20.3-net.fabricmc.yarn.1_20_3.1.20.3+build.1.jar:?]
	at net.minecraft.client.gui.widget.ClickableWidget.mouseClicked(ClickableWidget.java:145) ~[minecraft-merged-2da1a7ea61-1.20.3-net.fabricmc.yarn.1_20_3.1.20.3+build.1.jar:?]
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement.java:38) ~[minecraft-merged-2da1a7ea61-1.20.3-net.fabricmc.yarn.1_20_3.1.20.3+build.1.jar:?]
	at net.minecraft.client.gui.screen.TitleScreen.mouseClicked(TitleScreen.java:307) ~[minecraft-merged-2da1a7ea61-1.20.3-net.fabricmc.yarn.1_20_3.1.20.3+build.1.jar:?]
	at net.minecraft.client.Mouse.method_1611(Mouse.java:99) ~[minecraft-merged-2da1a7ea61-1.20.3-net.fabricmc.yarn.1_20_3.1.20.3+build.1.jar:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:414) ~[minecraft-merged-2da1a7ea61-1.20.3-net.fabricmc.yarn.1_20_3.1.20.3+build.1.jar:?]
	at net.minecraft.client.Mouse.onMouseButton(Mouse.java:99) ~[minecraft-merged-2da1a7ea61-1.20.3-net.fabricmc.yarn.1_20_3.1.20.3+build.1.jar:?]
	at net.minecraft.client.Mouse.method_22686(Mouse.java:180) ~[minecraft-merged-2da1a7ea61-1.20.3-net.fabricmc.yarn.1_20_3.1.20.3+build.1.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor.java:102) ~[minecraft-merged-2da1a7ea61-1.20.3-net.fabricmc.yarn.1_20_3.1.20.3+build.1.jar:?]
	at net.minecraft.client.Mouse.method_22684(Mouse.java:180) ~[minecraft-merged-2da1a7ea61-1.20.3-net.fabricmc.yarn.1_20_3.1.20.3+build.1.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.2.jar:build 13]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.2.jar:build 13]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509) ~[lwjgl-glfw-3.3.2.jar:build 13]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:238) ~[minecraft-merged-2da1a7ea61-1.20.3-net.fabricmc.yarn.1_20_3.1.20.3+build.1.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1352) ~[minecraft-merged-2da1a7ea61-1.20.3-net.fabricmc.yarn.1_20_3.1.20.3+build.1.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:888) ~[minecraft-merged-2da1a7ea61-1.20.3-net.fabricmc.yarn.1_20_3.1.20.3+build.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[minecraft-merged-2da1a7ea61-1.20.3-net.fabricmc.yarn.1_20_3.1.20.3+build.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[dev-launch-injector-0.2.1+build.8.jar:?]
[00:32:40] [Render thread/ERROR] (Mod Menu | ModsScreen) Error from mod 'customportals'
 java.lang.IncompatibleClassChangeError: class me.shedaniel.clothconfig2.gui.entries.DropdownBoxEntry$DefaultSelectionTopCellElement$1 overrides final method net.minecraft.client.gui.widget.ClickableWidget.render(Lnet/minecraft/client/gui/DrawContext;IIF)V
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at me.shedaniel.clothconfig2.impl.builders.DropdownMenuBuilder$TopCellElementBuilder.of(DropdownMenuBuilder.java:180) ~[cloth-config-fabric-12.0.111-fabric.jar:?]
	at me.lortseam.completeconfig.gui.cloth.ClothConfigScreenBuilder.lambda$static$35(ClothConfigScreenBuilder.java:158) ~[gui-cloth-2.5.2.jar:?]
	at me.lortseam.completeconfig.gui.ConfigScreenBuilder.createEntry(ConfigScreenBuilder.java:79) ~[base-2.5.2.jar:?]
	at me.lortseam.completeconfig.gui.cloth.ClothConfigScreenBuilder.buildEntry(ClothConfigScreenBuilder.java:307) ~[gui-cloth-2.5.2.jar:?]
	at me.lortseam.completeconfig.gui.cloth.ClothConfigScreenBuilder.buildCategoryList(ClothConfigScreenBuilder.java:294) ~[gui-cloth-2.5.2.jar:?]
	at me.lortseam.completeconfig.gui.cloth.ClothConfigScreenBuilder.build(ClothConfigScreenBuilder.java:284) ~[gui-cloth-2.5.2.jar:?]
	at dev.custom.portals.config.ModMenuIntegration.lambda$getModConfigScreenFactory$0(ModMenuIntegration.java:15) ~[main/:?]
	at com.terraformersmc.modmenu.ModMenu.getConfigScreen(ModMenu.java:62) ~[modmenu-9.0.0.jar:?]
	at com.terraformersmc.modmenu.gui.ModsScreen.init(ModsScreen.java:106) ~[modmenu-9.0.0.jar:?]
	at net.minecraft.client.gui.screen.Screen.init(Screen.java:298) ~[minecraft-merged-2da1a7ea61-1.20.3-net.fabricmc.yarn.1_20_3.1.20.3+build.1.jar:?]
	at net.minecraft.client.MinecraftClient.setScreen(MinecraftClient.java:1187) ~[minecraft-merged-2da1a7ea61-1.20.3-net.fabricmc.yarn.1_20_3.1.20.3+build.1.jar:?]
	at com.terraformersmc.modmenu.gui.widget.ModMenuButtonWidget.lambda$new$0(ModMenuButtonWidget.java:15) ~[modmenu-9.0.0.jar:?]
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget.java:95) ~[minecraft-merged-2da1a7ea61-1.20.3-net.fabricmc.yarn.1_20_3.1.20.3+build.1.jar:?]
	at net.minecraft.client.gui.widget.PressableWidget.onClick(PressableWidget.java:48) ~[minecraft-merged-2da1a7ea61-1.20.3-net.fabricmc.yarn.1_20_3.1.20.3+build.1.jar:?]
	at net.minecraft.client.gui.widget.ClickableWidget.mouseClicked(ClickableWidget.java:145) ~[minecraft-merged-2da1a7ea61-1.20.3-net.fabricmc.yarn.1_20_3.1.20.3+build.1.jar:?]
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement.java:38) ~[minecraft-merged-2da1a7ea61-1.20.3-net.fabricmc.yarn.1_20_3.1.20.3+build.1.jar:?]
	at net.minecraft.client.gui.screen.TitleScreen.mouseClicked(TitleScreen.java:307) ~[minecraft-merged-2da1a7ea61-1.20.3-net.fabricmc.yarn.1_20_3.1.20.3+build.1.jar:?]
	at net.minecraft.client.Mouse.method_1611(Mouse.java:99) ~[minecraft-merged-2da1a7ea61-1.20.3-net.fabricmc.yarn.1_20_3.1.20.3+build.1.jar:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:414) ~[minecraft-merged-2da1a7ea61-1.20.3-net.fabricmc.yarn.1_20_3.1.20.3+build.1.jar:?]
	at net.minecraft.client.Mouse.onMouseButton(Mouse.java:99) ~[minecraft-merged-2da1a7ea61-1.20.3-net.fabricmc.yarn.1_20_3.1.20.3+build.1.jar:?]
	at net.minecraft.client.Mouse.method_22686(Mouse.java:180) ~[minecraft-merged-2da1a7ea61-1.20.3-net.fabricmc.yarn.1_20_3.1.20.3+build.1.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor.java:102) ~[minecraft-merged-2da1a7ea61-1.20.3-net.fabricmc.yarn.1_20_3.1.20.3+build.1.jar:?]
	at net.minecraft.client.Mouse.method_22684(Mouse.java:180) ~[minecraft-merged-2da1a7ea61-1.20.3-net.fabricmc.yarn.1_20_3.1.20.3+build.1.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.2.jar:build 13]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.2.jar:build 13]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509) ~[lwjgl-glfw-3.3.2.jar:build 13]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:238) ~[minecraft-merged-2da1a7ea61-1.20.3-net.fabricmc.yarn.1_20_3.1.20.3+build.1.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1352) ~[minecraft-merged-2da1a7ea61-1.20.3-net.fabricmc.yarn.1_20_3.1.20.3+build.1.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:888) ~[minecraft-merged-2da1a7ea61-1.20.3-net.fabricmc.yarn.1_20_3.1.20.3+build.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[minecraft-merged-2da1a7ea61-1.20.3-net.fabricmc.yarn.1_20_3.1.20.3+build.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[dev-launch-injector-0.2.1+build.8.jar:?]
```

Here is my ModMenuIntegration class, for reference:
```java
public class ModMenuIntegration implements ModMenuApi {

    private static final ConfigScreenBuilder<?> configScreenBuilder = new ClothConfigScreenBuilder();

    @Override
    public ConfigScreenFactory<?> getModConfigScreenFactory() {
        return parent -> configScreenBuilder.build(parent, CustomPortals.getConfig());
    }
}
```

**Comment by Lortseam** [comment]
Please update to version 2.5.3 and try again.

**Comment by ghost** [comment]
That worked, thanks!
